# Generated by Django 5.2.8 on 2025-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.IntegerField(
                choices=[
                    (1, "Project Created"),
                    (2, "Project Transferred"),
                    (3, "Project Updated"),
                    (4, "Project Deleted"),
                    (5, "Task Created"),
                    (6, "Task Updated"),
                    (7, "Task Deleted"),
                    (8, "Team Joined"),
                    (9, "Member Added"),
                    (10, "Member Removed"),
                ]
            ),
        ),
    ]
