# Generated by Django 5.2.8 on 2025-12-01 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_activitylog_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAssignee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "Contributor"), (2, "Manager"), (3, "Lead")],
                        default=1,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_lead", models.BooleanField(default=False)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_project_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee_relations",
                        to="users.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignee_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="assignees",
            field=models.ManyToManyField(
                related_name="assigned_projects",
                through="users.ProjectAssignee",
                through_fields=("project", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "View Only"),
                            (2, "Edit Basic Info"),
                            (3, "Edit All"),
                            (4, "Admin"),
                        ],
                        default=1,
                    ),
                ),
                ("can_edit_name", models.BooleanField(default=False)),
                ("can_edit_description", models.BooleanField(default=False)),
                ("can_edit_dates", models.BooleanField(default=False)),
                ("can_edit_status", models.BooleanField(default=False)),
                ("can_assign_tasks", models.BooleanField(default=False)),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_transfer_project", models.BooleanField(default=False)),
                ("can_delete_project", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="users.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
    ]
