# Generated by Django 5.2.8 on 2025-12-03 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_projectassignee_project_assignees_projectpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
