# Generated by Django 5.2.8 on 2025-12-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_project_favorited_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
